### ISSUE TITLE
Rename this project to module-tagging-service?

### ISSUE THREAD

**Issue by lcarva** [fedora-modularity/message-tagging-service#34]
The intent of this service is to tag module builds in Koji. However, it does so by acting on a message. The current name may imply that messages are getting tagged instead of builds and may cause confusion.

I **think** initially the "M" in "MTS" was intended to be "module", not "message".

**Comment by tkdchen** [comment]
Rule has an attribute `type`. Currently, it is just `module`. Is there any original consideration to make this service general for tagging whatever builds? Or just only tag module build?

**Comment by ktdreyer** [comment]
I was just about to file a ticket about this very thing. The current name is very confusing.

**Comment by lcarva** [comment]
I'm closing this story because we don't have the resources to do this change anytime soon.

**Comment by ktdreyer** [comment]
Would you please consider re-opening this? I try my best to follow along with what Factory 2.0 is doing, but it's getting harder and harder for me to keep up. There are newer services all the time, and the names are overwhelming to me.

When I try to explain the build system to the rest of my team in Ceph, it's another barrier to us to understand or bother engaging with any of the work that Factory 2.0 is doing.

**Comment by lcarva** [comment]
@ktdreyer, given our list of priorities, I can't tell when we'll have the bandwidth to work on this. I understand that it causes confusion. If this ticket is left open, it will continue to get buried under higher priority work. I'd rather our backlog reflected an accurate picture of the work we'll likely get to, instead of giving stakeholders a false sense of hope.

As @tkdchen mentioned, this project is not necessarily tied to modules (even though that's exactly how we use it today). One could make the case that renaming should not happen.

**Comment by ktdreyer** [comment]
That's fair. Thanks @lcarva .
